runtime: python
env: flex

runtime_config:
  python_version: 3

entrypoint: gunicorn -b :$PORT api:app --timeout 120

resources:
  cpu: 4
  memory_gb: 4
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
