name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Authorize Docker push
      run: gcloud auth configure-docker
    
    - name: Build and Push Container
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-service:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-service:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy api-service \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-service:${{ github.sha }} \
          --platform managed \
          --region asia-southeast2 \
          --allow-unauthenticated \
          --memory 512Mi
